In [2]:
import numpy as np

In [5]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [7]:
multi = np.array([[1,2,3], [4,5,6], [7,8,9]])
multi

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
print(multi)
print()
print(multi.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [21]:
zeros = np.zeros((4,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
multi[0][0] = 3

In [24]:
multi

array([[3, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
a = np.floor(2.43)

In [28]:
a

2.0

In [29]:
2.4 % 2

0.3999999999999999

In [33]:
2.4 - 0.399999999999999

2.000000000000001